__all__ = [
    "CC_COUNT",
    "NOTES_COUNT",
    "SEMITONES_IN_OCTAVE",
    "MIN_SEMI_OFFSET",
    "MAX_SEMI_OFFSET",
    "CHANNEL_VOL_STEP",
    "MIXER_TRACK_VOL_STEP",
]

CC_COUNT = 128

NOTES_COUNT = 16

MIN_OCTAVE = -5
MAX_OCTAVE = 5

SEMITONES_IN_OCTAVE = 12

MIN_SEMI_OFFSET = SEMITONES_IN_OCTAVE * MIN_OCTAVE
MAX_SEMI_OFFSET = SEMITONES_IN_OCTAVE * MAX_OCTAVE

CHANNEL_VOL_STEP = 0.03125

MIXER_TRACK_VOL_STEP = 0.012125
