"""Constants"""

__all__ = [
    "GROUPS_RANGE",
    "MIN_OCTAVE",
    "MAX_OCTAVE",
    "SEMITONES_IN_OCTAVE",
    "MIN_SEMI_OFFSET",
    "MAX_SEMI_OFFSET",
]

GROUPS_RANGE = range(100, 108)  # CC numbers for groups A to H

MIN_OCTAVE = -5
MAX_OCTAVE = 5

SEMITONES_IN_OCTAVE = 12

MIN_SEMI_OFFSET = SEMITONES_IN_OCTAVE * MIN_OCTAVE
MAX_SEMI_OFFSET = SEMITONES_IN_OCTAVE * MAX_OCTAVE
