"""Maschine MK3 Control Change (CC) Numbers"""

# -------- CONTROL BUTTONS SECTION -------- #
CC_CHANNEL = 34
CC_PLUGIN = 35
CC_ARRANGER = 36
CC_MIXER = 37
CC_BROWSER = 38
CC_SAMPLING = 39
CC_FILE_SAVE = 40
CC_SETTINGS = 41
CC_MACRO_SET = 43


# -------- EDIT (ENCODER) SECTION -------- #
CC_ENCODER_PUSH = 7
CC_ENCODER_TURN = 8
CC_ENCODER_UP = 30
CC_ENCODER_RIGHT = 31
CC_ENCODER_DOWN = 32
CC_ENCODER_LEFT = 33

CC_ENCODER_VOLUME = 44
CC_ENCODER_SWING = 45
CC_ENCODER_TEMPO = 47

# -------- TOUCH STRIP SECTION -------- #
CC_TOUCH_STRIP = 1

CC_LOCK = 48
CC_PITCH = 49
CC_MOD = 50
CC_PERFORM = 51
CC_NOTES = 52

# -------- GROUP SECTION -------- #
CC_PAD_GROUP_A = 100
CC_PAD_GROUP_B = 101
CC_PAD_GROUP_C = 102
CC_PAD_GROUP_D = 103
CC_PAD_GROUP_E = 104
CC_PAD_GROUP_F = 105
CC_PAD_GROUP_G = 106
CC_PAD_GROUP_H = 107

# -------- TRANSPORT SECTION -------- #
CC_RESTART = CC_LOOP = 53
CC_ERASE = 54
CC_TAP = 55
CC_FOLLOW = 56
CC_PLAY = 57
CC_REC = 58
CC_STOP = 59

# -------- PAD SECTION -------- #
CC_FIXED_VEL = 80

# Pad Modes
CC_PAD_MODE = 81
CC_KEYBOARD_MODE = 82
CC_STEP_MODE = 83
CC_CHORDS_MODE = 84

CC_SCENE = 85
CC_PATTERN = 86
CC_EVENTS = 87
CC_VARIATION = 88
CC_DUPLICATE = 89
CC_SELECT = 90
CC_SOLO = 91
CC_MUTE = 92

# ---- KNOB PAGE SECTION ---- #
CC_OCTAVE_DOWN = 26
CC_OCTAVE_UP = 27
CC_SEMI_DOWN = 28
CC_SEMI_UP = 29

CC_MIX_TRACK = 70
CC_MIX_VOLUME = 71
CC_MIX_PAN = 72
CC_MIX_STEREO = 73
CC_CHAN_SEL = 74
CC_CHAN_VOL = 75
CC_CHAN_PAN = 76
CC_FIX_VEL = 77
